spring:
  datasource:
    url: ${DB_STRING}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
okta:
  oauth2:
    # Replace with the domain of your Auth0 tenant.
    issuer: ${AUTH0_ISSUER}
    # Replace with the API Identifier for your Auth0 API.
    audience: ${AUTH0_AUDIENCE}
zuul:
  ratelimit:
    enabled: true
    repository: JPA
    behind-proxy: true
    policy-list:
      default:
          limit: 10
          refresh-interval: 60
          type:
            - user
            - url
